import { Header } from "@/components/Header/Header";
import { Albuns } from "@/components/TopAlbuns/Albuns";
import { getAuthParams, getUser } from "@/redux/request-slice";
import { RootState } from "@/redux/store";
import Head from "next/head";
import styles from "../Home/Home.module.css";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";

export default function Home() {
  const tracks = useSelector((state: RootState) => state.requests.tracks);
  const dispatch = useDispatch();
  useEffect(() => {
    const repeatFetch = () => {
      const params = window.location.pathname;
      dispatch(getAuthParams(params));
      // dispatch(getUser());
    };
    const intervalId = setTimeout(() => {
      repeatFetch();
      clearTimeout(intervalId);
    }, 6000);

    return () => clearTimeout(intervalId);
  }, []);

  return (
    <>
      <Head>
        <title>S'charts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.container}>
        <Albuns albunsType="Ouvidas Recentemente" contentType={tracks} />
        <Albuns albunsType="Artistas mais Ouvidos" contentType={tracks} />
      </main>
    </>
  );
}
