import { Header } from "@/components/Header/Header";
import { Albuns } from "@/components/TopAlbuns/Albuns";
import { getAuthParams } from "@/redux/request-slice";
import Head from "next/head";
import router, { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";

export default function Home() {
  const dispatch = useDispatch();
  useEffect(() => {
    const params = window.location.pathname;
    dispatch(getAuthParams(params));
  }, []);
  return (
    <>
      <Head>
        <title>S'charts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="container">
        <Albuns />
      </main>
    </>
  );
}
