import { Header } from "@/components/Header/Header";
import { Albuns } from "@/components/TopAlbuns/Albuns";
import { getAuthParams } from "@/redux/request-slice";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";

// const SCOPES_URL_PARAMS = SCOPES.join(SPACE_DELIMITER);

export default function Home() {
  const dispatch = useDispatch();
  const isLogged = useSelector((logged: any) => logged.requests.isLoggedIn);

  useEffect(() => {
    if (window.location.hash) {
      dispatch(getAuthParams(window.location.hash));
    }
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="container">
        <Albuns />
      </main>
    </>
  );
}
